# Login Image
FROM ubiquitycluster/rocky-slurm-base:latest

# Install SSH Server
RUN dnf update && dnf install -y \
    pip \
    openssh-server && \
    dnf clean all

# Install Easy Build
RUN  pip install easybuild ensurepath

# Ensure Munge is set up
RUN chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key

# Expose Port 22 and 6817 for slurm for login
EXPOSE 22 6817

# Start command
CMD ["bash", "-c","cp /tmp/munge.key /etc/munge/ && munged --force && \
              cp /etc/slurm/slurm.conf /usr/local/slurm/etc/ && \
              service ssh start && sssd -d 6 --logger=files && sleep infinity"]
